import "./globals.css";
import AuthChecker from "@/components/AuthChecker";
import LayoutSwitcher from "@/components/LayoutSwitcher";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <AuthChecker>
          <LayoutSwitcher>
            {children}
          </LayoutSwitcher>
        </AuthChecker>
      </body>
    </html>
  );
}